# Generated by Django 2.2.5 on 2019-09-11 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_kitchen_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
